# Generated by Django 3.2.12 on 2023-09-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230914_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='date',
            field=models.DateField(verbose_name='Play date'),
        ),
    ]
